import { FIREBASE_CONFIG, DEFAULT_COMPANY_ID, adminEmail } from './firebase-config.js';
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, collection, doc, addDoc, updateDoc, deleteDoc, onSnapshot, serverTimestamp, getDoc, getDocs, writeBatch } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const $=id=>document.getElementById(id);
const app=getApps().length?getApps()[0]:initializeApp(FIREBASE_CONFIG);
const auth=getAuth(app),db=getFirestore(app),companyId=DEFAULT_COMPANY_ID,EXPECTED=adminEmail('diva','1');
const c=n=>collection(db,'empresas',companyId,n),d=(n,id)=>doc(db,'empresas',companyId,n,id);
const st={customers:[],inventory:[],media:[],orders:[],items:[],photos:[],editId:'',stockLocked:false,unsubs:[],authorized:false,started:false,bound:false,mediaLoaded:false,draftRestored:false,customersLoaded:false,ordersLoaded:false,pendingCustomerId:'',customerPickerReady:false};
const iso=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const debounce=(fn,ms=180)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function notify(msg,type='ok'){if(typeof window.notificar==='function')return window.notificar(msg,type==='error'?'var(--red)':'var(--green)');const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),2800)}
async function audit(action,target,details={}){try{await addDoc(c('audit'),{action,target,details,actor:auth.currentUser?.email||'',createdAt:serverTimestamp(),createdAtISO:iso(),createdAtMs:Date.now()})}catch{}}
function customerSnapshot(){const x=st.customers.find(v=>v.id===$('woCustomer')?.value);return x?{id:x.id,code:x.code||'',name:x.name||'',document:x.document||'',phone:x.phone||'',email:x.email||'',address:x.address||'',stateRegistration:x.stateRegistration||''}:{id:'',code:'',name:'',document:'',phone:'',email:'',address:'',stateRegistration:''}}
function statusLabel(v){return({rascunho:'Rascunho',aguardando:'Aguardando',aprovado:'Aprovado',execucao:'Em execução',concluido:'Concluído',recusado:'Recusado',cancelado:'Cancelado'})[v]||v||'-'}
function typeLabel(v){return v==='os'?'Ordem de Serviço':'Orçamento'}
function newNumber(type=$('woType')?.value||'orcamento'){const prefix=type==='os'?'OS':'ORC',nums=st.orders.filter(x=>(x.number||'').toUpperCase().startsWith(prefix)).map(x=>Number(String(x.number||'').replace(/\D/g,''))||0);return`${prefix}-${String(Math.max(0,...nums)+1).padStart(6,'0')}`}
function totals(){const calc=kind=>st.items.filter(x=>kind?x.kind===kind:!['part','labor'].includes(x.kind)).reduce((a,x)=>a+Math.max(0,Number(x.qty||0)*Number(x.unitPrice||0)-Number(x.discount||0)),0),parts=calc('part'),labor=calc('labor'),services=calc(''),subtotal=parts+labor+services,discount=Math.max(0,Number($('woDiscount')?.value||0)),total=Math.max(0,subtotal-discount);return{parts,labor,services,subtotal,discount,total}}
function updateSideStatus(){const v=$('woStatus')?.value||'rascunho',e=$('woSideStatus');if(e){e.textContent=statusLabel(v).toUpperCase();e.className=`pill wo-status ${v}`}}
function updateTotals(){if(!$('woTotal'))return;const t=totals();$('woPartsTotal').textContent=money(t.parts);$('woLaborTotal').textContent=money(t.labor);$('woSubtotal').textContent=money(t.subtotal);$('woTotal').textContent=money(t.total);$('woItemCount').textContent=`${st.items.length} ${st.items.length===1?'item':'itens'}`;updateSideStatus()}
function fillCustomers(){if(!$('woCustomer'))return;let cur=st.pendingCustomerId||$('woCustomer').value||'';$('woCustomer').innerHTML='<option value="">Selecione um cliente...</option>'+st.customers.map(x=>`<option value="${x.id}">${esc(x.code?x.code+' • ':'')}${esc(x.name)}</option>`).join('');if([...$('woCustomer').options].some(o=>o.value===cur)){$('woCustomer').value=cur;if(st.pendingCustomerId===cur)st.pendingCustomerId=''}else $('woCustomer').value='';ensureCustomerPicker();renderCustomerPicker($('woCustomerSearch')?.value||'');updateCustomerUI()}

function customerSearchText(x){return norm([x.code,x.name,x.document,x.phone,x.email,x.address,x.stateRegistration,x.id].filter(Boolean).join(' '))}
function customerRecentMs(x){return st.orders.filter(o=>(o.customerId||o.customer?.id)===x.id).reduce((m,o)=>Math.max(m,Number(o.updatedAtMs||o.createdAtMs||0)),0)}
function customerScore(x,q){if(!q)return customerRecentMs(x)>0?10000000000000+customerRecentMs(x):0;const nq=norm(q),digits=String(q).replace(/\D/g,''),name=norm(x.name),code=norm(x.code),doc=String(x.document||'').replace(/\D/g,''),phone=String(x.phone||'').replace(/\D/g,'');let score=0;if(code===nq)score+=1000;if(doc&&digits&&doc===digits)score+=950;if(name===nq)score+=900;if(code.startsWith(nq))score+=700;if(name.startsWith(nq))score+=650;if(doc&&digits&&doc.startsWith(digits))score+=600;if(phone&&digits&&phone.startsWith(digits))score+=550;if(customerSearchText(x).includes(nq))score+=250;return score}
function renderCustomerPicker(query=''){
  const box=$('woCustomerResults');if(!box)return;
  const q=query.trim();
  let rows=st.customers.map(x=>({x,score:customerScore(x,q)})).filter(r=>!q||r.score>0);
  rows.sort((a,b)=>b.score-a.score||String(a.x.name||'').localeCompare(String(b.x.name||''),'pt-BR'));
  rows=rows.slice(0,18);
  box.innerHTML=rows.map(({x})=>{const recent=st.orders.filter(o=>(o.customerId||o.customer?.id)===x.id).length;return`<button type="button" class="wo-customer-result" data-customer-id="${esc(x.id)}"><span class="wo-customer-result-main"><strong>${esc(x.name||'Sem nome')}</strong><small>${esc(x.code||'Sem código')}${x.document?' • '+esc(x.document):''}</small></span><span class="wo-customer-result-contact">${x.phone?'<b>'+esc(x.phone)+'</b>':''}${x.email?'<small>'+esc(x.email)+'</small>':''}</span>${recent?`<span class="wo-customer-result-count">${recent} atendimento${recent===1?'':'s'}</span>`:''}</button>`}).join('')||'<div class="wo-customer-no-result"><i class="fa-solid fa-user-slash"></i><strong>Nenhum cliente encontrado</strong><span>Tente código, nome, CPF/CNPJ, telefone, e-mail ou endereço.</span></div>';
  box.querySelectorAll('[data-customer-id]').forEach(b=>b.onclick=()=>selectCustomer(b.dataset.customerId));
}
function closeCustomerPicker(){const p=$('woCustomerPanel');if(p)p.hidden=true;$('woCustomerPicker')?.classList.remove('open')}
function openCustomerPicker(){const p=$('woCustomerPanel'),input=$('woCustomerSearch');if(!p)return;p.hidden=false;$('woCustomerPicker')?.classList.add('open');renderCustomerPicker(input?.value||'');setTimeout(()=>input?.focus(),0)}
function selectCustomer(id){const sel=$('woCustomer');if(!sel)return;sel.value=id||'';sel.dispatchEvent(new Event('change',{bubbles:true}));closeCustomerPicker();updateCustomerUI();saveDraftDebounced()}
function openSelectedCustomerInClients(){const x=st.customers.find(v=>v.id===$('woCustomer')?.value);if(!x)return;document.querySelector('[data-go="clients"]')?.click();setTimeout(()=>{const q=document.getElementById('customerSearch');if(q){q.value=x.code||x.name||x.document||'';q.dispatchEvent(new Event('input',{bubbles:true}));q.focus()}},120)}
function updateCustomerUI(){
  const id=$('woCustomer')?.value||'',x=st.customers.find(v=>v.id===id),trigger=$('woCustomerTrigger'),summary=$('woCustomerSummary');
  if(trigger){trigger.classList.toggle('selected',!!x);trigger.innerHTML=x?`<span><strong>${esc(x.name||'Cliente')}</strong><small>${esc(x.code||'Sem código')}${x.document?' • '+esc(x.document):''}</small></span><i class="fa-solid fa-chevron-down"></i>`:`<span><strong>Localizar cliente</strong><small>Busque por ID, nome, CPF/CNPJ, telefone ou e-mail</small></span><i class="fa-solid fa-chevron-down"></i>`}
  if(!summary)return;
  if(!x){summary.hidden=true;summary.innerHTML='';return}
  const history=st.orders.filter(o=>(o.customerId||o.customer?.id)===x.id).sort((a,b)=>Number(b.updatedAtMs||b.createdAtMs||0)-Number(a.updatedAtMs||a.createdAtMs||0)).slice(0,3);
  summary.hidden=false;summary.innerHTML=`<div class="wo-customer-summary-main"><div><span>CLIENTE SELECIONADO</span><strong>${esc(x.name||'')}</strong><small>${[x.code,x.document,x.phone,x.email].filter(Boolean).map(esc).join(' • ')||'Sem dados adicionais'}</small></div><button type="button" id="woCustomerOpenRecord" class="wo-customer-record-btn"><i class="fa-solid fa-address-card"></i> Cadastro</button></div>${history.length?`<div class="wo-customer-history"><span>Últimos atendimentos</span>${history.map(o=>`<button type="button" data-history-order="${esc(o.id)}"><strong>${esc(o.number||'Atendimento')}</strong><small>${esc([o.machine?.brand,o.machine?.model].filter(Boolean).join(' ')||o.machine?.type||'Máquina não informada')} • ${esc(statusLabel(o.status))}</small></button>`).join('')}</div>`:''}`;
  $('woCustomerOpenRecord')?.addEventListener('click',openSelectedCustomerInClients);
  summary.querySelectorAll('[data-history-order]').forEach(b=>b.onclick=()=>editOrder(b.dataset.historyOrder));
}
function ensureCustomerPicker(){
  const select=$('woCustomer');if(!select||st.customerPickerReady)return;st.customerPickerReady=true;select.hidden=true;
  const host=document.createElement('div');host.id='woCustomerPicker';host.className='wo-customer-picker';host.innerHTML=`<button type="button" class="wo-customer-trigger" id="woCustomerTrigger"><span><strong>Localizar cliente</strong><small>Busque por ID, nome, CPF/CNPJ, telefone ou e-mail</small></span><i class="fa-solid fa-chevron-down"></i></button><div class="wo-customer-panel" id="woCustomerPanel" hidden><div class="wo-customer-searchbar"><i class="fa-solid fa-magnifying-glass"></i><input id="woCustomerSearch" type="search" autocomplete="off" placeholder="Digite ID, nome, CPF/CNPJ, telefone, e-mail, endereço..."><kbd>F2</kbd></div><div class="wo-customer-results" id="woCustomerResults"></div><div class="wo-customer-panel-foot"><button type="button" id="woCustomerCreate"><i class="fa-solid fa-user-plus"></i>Cadastrar novo cliente</button><span>Máx. 18 resultados para manter rápido</span></div></div>`;
  select.before(host);const summary=document.createElement('div');summary.id='woCustomerSummary';summary.className='wo-customer-summary';summary.hidden=true;select.after(summary);
  $('woCustomerTrigger').onclick=()=>{if($('woCustomerPanel').hidden)openCustomerPicker();else closeCustomerPicker()};
  $('woCustomerSearch').oninput=debounce(e=>renderCustomerPicker(e.target.value),45);
  $('woCustomerSearch').onkeydown=e=>{if(e.key==='Escape')closeCustomerPicker();if(e.key==='Enter'){const first=$('woCustomerResults')?.querySelector('[data-customer-id]');if(first){e.preventDefault();selectCustomer(first.dataset.customerId)}}};
  $('woCustomerCreate').onclick=()=>{closeCustomerPicker();const d=document.querySelector('.quick-customer');if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('woQuickName')?.focus(),250)}};
  select.addEventListener('change',updateCustomerUI);
  document.addEventListener('click',e=>{const picker=$('woCustomerPicker');if(picker&&!picker.contains(e.target))closeCustomerPicker()});
  document.addEventListener('keydown',e=>{if(e.key==='F2'&&document.querySelector('[data-section="orders"]')?.classList.contains('active')){e.preventDefault();openCustomerPicker()}});
}

function fillInventory(){if(!$('woStockItem'))return;const cur=$('woStockItem').value||'',q=($('woStockSearch')?.value||'').toLowerCase().trim(),rows=st.inventory.filter(x=>!q||[x.name,x.code,x.category,x.brand].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>{const sa=/stihl/i.test(`${a.name} ${a.category} ${a.brand}`)?1:0,sb=/stihl/i.test(`${b.name} ${b.category} ${b.brand}`)?1:0;return sb-sa||String(a.name||'').localeCompare(String(b.name||''))});$('woStockItem').innerHTML='<option value="">Item manual...</option>'+rows.slice(0,250).map(x=>`<option value="${x.id}">${esc(x.code||'SEM CÓD.')} • ${esc(x.name||'Item')} (${Number(x.qty||0)})</option>`).join('');$('woStockItem').value=cur}
async function loadMedia(){if(st.mediaLoaded)return;st.mediaLoaded=true;try{const snap=await getDocs(c('media'));st.media=snap.docs.map(v=>({id:v.id,...v.data()})).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));fillMedia()}catch(e){st.mediaLoaded=false;console.error(e);notify('Não foi possível carregar a biblioteca de Mídia.','error')}}
function fillMedia(){if(!$('woItemImage')||!$('woPhotoSelect'))return;const opts='<option value="">Sem imagem</option>'+st.media.map(x=>`<option value="media:${x.id}">${esc(x.name||x.id)}</option>`).join('');$('woItemImage').innerHTML=opts;$('woPhotoSelect').innerHTML='<option value="">Escolha uma imagem...</option>'+st.media.map(x=>`<option value="media:${x.id}">${esc(x.name||x.id)}</option>`).join('')}
function stockSelected(){const x=st.inventory.find(v=>v.id===$('woStockItem').value);if(!x)return;$('woItemDesc').value=x.name||'';$('woItemCode').value=x.code||'';$('woItemPrice').value=Number(x.price||0)||'';$('woItemKind').value='part'}
function clearItem(){['woStockItem','woItemDesc','woItemCode','woItemPrice','woItemDiscount','woItemNotes'].forEach(id=>{if($(id))$(id).value=''});$('woItemQty').value='1';$('woItemKind').value='part';if($('woItemImage'))$('woItemImage').value=''}
function itemTotal(x){return Math.max(0,Number(x.qty||0)*Number(x.unitPrice||0)-Number(x.discount||0))}
function renderItems(){if(!$('woItemRows'))return;$('woItemRows').innerHTML=st.items.map((x,i)=>`<tr><td><span class="wo-kind ${esc(x.kind)}">${esc(({part:'Peça',labor:'Mão de obra',service:'Serviço',other:'Outro'})[x.kind]||x.kind)}</span><strong>${esc(x.description)}</strong>${x.notes?`<small>${esc(x.notes)}</small>`:''}</td><td>${esc(x.sku||'-')}</td><td>${Number(x.qty||0)}</td><td>${x.priceProvided===false?'—':money(x.unitPrice)}</td><td>${Number(x.discount||0)?money(x.discount):'—'}</td><td><strong>${x.priceProvided===false?'—':money(itemTotal(x))}</strong></td><td><button class="sales-icon-btn danger" type="button" ${st.stockLocked?'disabled title="Itens bloqueados após baixa de estoque"':''} onclick="KleimpaulOrders.removeItem(${i})"><i class="fa-solid fa-trash"></i></button></td></tr>`).join('')||'<tr><td colspan="7" class="wo-empty">Nenhum item adicionado.</td></tr>';updateTotals();saveDraftDebounced()}
function addItem(){if(st.stockLocked)return notify('Os itens ficam bloqueados depois da baixa de estoque.','error');const desc=$('woItemDesc').value.trim();if(!desc)return notify('Informe a peça, serviço ou mão de obra.','error');const inv=st.inventory.find(x=>x.id===$('woStockItem').value),rawPrice=$('woItemPrice').value;st.items.push({kind:$('woItemKind').value,inventoryId:inv?.id||'',description:desc,sku:$('woItemCode').value.trim()||inv?.code||'',qty:Math.max(.001,Number($('woItemQty').value||1)),unitPrice:Math.max(0,Number(rawPrice||0)),priceProvided:rawPrice!=='',discount:Math.max(0,Number($('woItemDiscount').value||0)),image:$('woItemImage').value||'',notes:$('woItemNotes').value.trim()});clearItem();renderItems()}
function renderPhotos(){if(!$('woPhotos'))return;$('woPhotos').innerHTML=st.photos.map((ref,i)=>{const id=String(ref).replace(/^media:/,'');const m=st.media.find(x=>x.id===id);return`<div class="wo-photo-chip"><span><i class="fa-solid fa-image"></i>${esc(m?.name||ref)}</span><button type="button" onclick="KleimpaulOrders.removePhoto(${i})"><i class="fa-solid fa-xmark"></i></button></div>`}).join('')||'<small class="wo-muted">Nenhuma foto.</small>';if($('woPhotoCount'))$('woPhotoCount').textContent=String(st.photos.length);saveDraftDebounced()}
async function addPhoto(){await loadMedia();const v=$('woPhotoSelect').value;if(!v)return;if(st.photos.includes(v))return notify('Esta imagem já foi adicionada.','error');if(st.photos.length>=8)return notify('Use no máximo 8 imagens por ordem.','error');st.photos.push(v);$('woPhotoSelect').value='';renderPhotos()}
function currentData(){const t=totals();return{number:$('woNumber').value.trim(),documentType:$('woType').value,date:$('woDate').value,validUntil:$('woValidUntil').value,expectedDate:$('woExpectedDate').value,status:$('woStatus').value,priority:$('woPriority').value,technician:$('woTechnician').value.trim(),customerId:$('woCustomer').value,customer:customerSnapshot(),machine:{type:$('woMachineType').value.trim(),brand:$('woBrand').value.trim(),model:$('woModel').value.trim(),serial:$('woSerial').value.trim(),engineNumber:$('woEngineNumber').value.trim(),asset:$('woAsset').value.trim(),year:$('woYear').value.trim(),hourMeter:$('woHourMeter').value.trim(),fuel:$('woFuel').value,condition:$('woCondition').value.trim(),accessories:$('woAccessories').value.trim()},complaint:$('woComplaint').value.trim(),diagnosis:$('woDiagnosis').value.trim(),requestedWork:$('woRequestedWork').value.trim(),performedWork:$('woPerformedWork').value.trim(),items:st.items,photos:st.photos,discount:t.discount,subtotal:t.subtotal,partsTotal:t.parts,laborTotal:t.labor,servicesTotal:t.services,total:t.total,warrantyDays:Math.max(0,Number($('woWarranty').value||0)),publicNotes:$('woPublicNotes').value.trim(),internalNotes:$('woInternalNotes').value.trim(),approval:{name:$('woApprovalName').value.trim(),date:$('woApprovalDate').value,method:$('woApprovalMethod').value,notes:$('woApprovalNotes').value.trim()},useStock:$('woUseStock').checked,updatedAtISO:iso()}}
function validate(data){if(!data.customerId)return'Escolha ou cadastre o cliente.';if(!data.machine.type&&!data.machine.model)return'Informe o tipo ou modelo da máquina.';if(!data.number)return'Informe o número do documento.';return''}
async function applyStock(data,previous){if(!data.useStock||data.status!=='concluido'||previous?.stockApplied)return false;const items=data.items.filter(x=>x.kind==='part'&&x.inventoryId);if(!items.length)return false;const grouped=new Map();for(const item of items)grouped.set(item.inventoryId,(grouped.get(item.inventoryId)||0)+Number(item.qty||0));const batch=writeBatch(db);for(const[inventoryId,qty]of grouped){const ref=d('inventory',inventoryId),snap=await getDoc(ref);if(!snap.exists())throw new Error('Uma peça vinculada ao estoque não existe mais.');const row=snap.data(),available=Number(row.qty||0);if(available<qty)throw new Error(`Estoque insuficiente para ${row.name||row.code||'uma peça'}: disponível ${available}, necessário ${qty}.`);batch.update(ref,{qty:available-qty,updatedAt:serverTimestamp(),updatedAtISO:iso()})}await batch.commit();return true}
async function restoreStock(order){if(!order?.stockApplied||order?.stockRestored)return;const items=(order.items||[]).filter(x=>x.kind==='part'&&x.inventoryId),grouped=new Map();for(const item of items)grouped.set(item.inventoryId,(grouped.get(item.inventoryId)||0)+Number(item.qty||0));const batch=writeBatch(db);for(const[inventoryId,qty]of grouped){const ref=d('inventory',inventoryId),snap=await getDoc(ref);if(!snap.exists())continue;const row=snap.data();batch.update(ref,{qty:Number(row.qty||0)+qty,updatedAt:serverTimestamp(),updatedAtISO:iso()})}await batch.commit()}
async function save(forceStatus=''){const id=$('woId').value,data=currentData();if(forceStatus)data.status=forceStatus;const err=validate(data);if(err)return notify(err,'error');if(st.orders.some(x=>x.id!==id&&String(x.number||'').toUpperCase()===data.number.toUpperCase()))return notify('Já existe um documento com este número.','error');const prev=id?st.orders.find(x=>x.id===id):null;try{const stockApplied=await applyStock(data,prev),payload={...data,stockApplied:prev?.stockApplied||stockApplied||false,stockRestored:false,updatedAt:serverTimestamp(),updatedAtISO:iso(),updatedAtMs:Date.now()};let savedId=id;if(id)await updateDoc(d('work_orders',id),payload);else{const ref=await addDoc(c('work_orders'),{...payload,createdAt:serverTimestamp(),createdAtISO:iso(),createdAtMs:Date.now()});savedId=ref.id;$('woId').value=savedId}await audit(id?'workorder.update':'workorder.create',data.number,{status:data.status,total:data.total,customer:data.customer?.name});localStorage.removeItem('kleimpaul_work_order_draft');notify(data.status==='concluido'?'O.S. concluída e salva.':'Documento salvo.');return savedId}catch(e){console.error(e);notify(e.message||'Falha ao salvar.','error')}}
function setDefaults(){const now=new Date(),plus=days=>{const d=new Date(now);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};$('woDate').value=now.toISOString().slice(0,10);$('woValidUntil').value=plus(10);$('woApprovalDate').value='';$('woExpectedDate').value='';$('woBrand').value='STIHL';$('woFuel').value='';$('woWarranty').value='90';$('woDiscount').value='0';$('woUseStock').checked=true;$('woStatus').value='rascunho';$('woPriority').value='normal';$('woType').value='orcamento';$('woNumber').value=newNumber('orcamento');updateSideStatus()}
function clearForm(){st.editId='';st.stockLocked=false;$('woId').value='';['woTechnician','woMachineType','woModel','woSerial','woEngineNumber','woAsset','woYear','woHourMeter','woCondition','woAccessories','woComplaint','woDiagnosis','woRequestedWork','woPerformedWork','woPublicNotes','woInternalNotes','woApprovalName','woApprovalNotes'].forEach(id=>{if($(id))$(id).value=''});$('woCustomer').value='';updateCustomerUI();$('woApprovalMethod').value='';st.items=[];st.photos=[];setDefaults();renderItems();renderPhotos();$('woEditState').textContent='NOVO';saveDraftDebounced()}
function editOrder(id){const x=st.orders.find(v=>v.id===id);if(!x)return;st.editId=id;st.stockLocked=!!x.stockApplied&&!x.stockRestored;$('woId').value=id;$('woNumber').value=x.number||'';$('woType').value=x.documentType||'orcamento';$('woDate').value=x.date||'';$('woValidUntil').value=x.validUntil||'';$('woExpectedDate').value=x.expectedDate||'';$('woStatus').value=x.status||'rascunho';$('woPriority').value=x.priority||'normal';$('woTechnician').value=x.technician||'';$('woCustomer').value=x.customerId||x.customer?.id||'';updateCustomerUI();$('woMachineType').value=x.machine?.type||'';$('woBrand').value=x.machine?.brand||'STIHL';$('woModel').value=x.machine?.model||'';$('woSerial').value=x.machine?.serial||'';$('woEngineNumber').value=x.machine?.engineNumber||'';$('woAsset').value=x.machine?.asset||'';$('woYear').value=x.machine?.year||'';$('woHourMeter').value=x.machine?.hourMeter||'';$('woFuel').value=x.machine?.fuel||'';$('woCondition').value=x.machine?.condition||'';$('woAccessories').value=x.machine?.accessories||'';$('woComplaint').value=x.complaint||'';$('woDiagnosis').value=x.diagnosis||'';$('woRequestedWork').value=x.requestedWork||'';$('woPerformedWork').value=x.performedWork||'';$('woDiscount').value=x.discount||0;$('woWarranty').value=x.warrantyDays||0;$('woPublicNotes').value=x.publicNotes||'';$('woInternalNotes').value=x.internalNotes||'';$('woApprovalName').value=x.approval?.name||'';$('woApprovalDate').value=x.approval?.date||'';$('woApprovalMethod').value=x.approval?.method||'';$('woApprovalNotes').value=x.approval?.notes||'';$('woUseStock').checked=x.useStock!==false;st.items=(x.items||[]).map(v=>({...v,priceProvided:v.priceProvided!==false}));st.photos=[...(x.photos||[])];renderItems();renderPhotos();$('woEditState').textContent=x.stockApplied?'ESTOQUE BAIXADO':'EDITANDO';updateSideStatus();document.querySelector('[data-go="orders"]')?.click();window.scrollTo({top:0,behavior:'smooth'})}
async function cancelOrder(id){const x=st.orders.find(v=>v.id===id);if(!x||x.status==='cancelado')return;if(!confirm(`Cancelar ${x.number}?`))return;try{await restoreStock(x);await updateDoc(d('work_orders',id),{status:'cancelado',stockRestored:!!x.stockApplied,updatedAt:serverTimestamp(),updatedAtISO:iso()});await audit('workorder.cancel',x.number,{stockRestored:!!x.stockApplied});notify('Documento cancelado.')}catch(e){console.error(e);notify('Não foi possível cancelar.','error')}}
async function deleteOrder(id){const x=st.orders.find(v=>v.id===id);if(!x)return;const sec=window.KleimpaulSecurity;if(!sec?.authorizeDelete)return notify('Módulo de segurança indisponível.','error');if(!await sec.authorizeDelete({collectionName:'work_orders',id,data:x,label:x.number||'Orçamento / O.S.',message:'Excluir definitivamente este orçamento/O.S.? Uma cópia será criada no Cofre antes da exclusão.'}))return;await deleteDoc(d('work_orders',id));await audit('workorder.delete',x.number);notify('Documento excluído com cópia de segurança.')}
function printOrder(id){window.open(`ordem.html?id=${encodeURIComponent(id)}`,'_blank')}
function printDraft(){saveDraftNow();window.open('ordem.html?draft=1','_blank')}
function duplicateOrder(id){const x=st.orders.find(v=>v.id===id);if(!x)return;editOrder(id);$('woId').value='';$('woType').value='orcamento';$('woNumber').value=newNumber('orcamento');$('woStatus').value='rascunho';$('woEditState').textContent='CÓPIA';st.editId='';st.stockLocked=false;updateSideStatus()}
function convertToOS(id){const x=st.orders.find(v=>v.id===id);if(!x)return;editOrder(id);$('woId').value='';$('woType').value='os';$('woNumber').value=newNumber('os');$('woStatus').value='aprovado';$('woEditState').textContent='NOVA O.S.';st.editId='';st.stockLocked=false;updateSideStatus()}
function orderFiltered(){const q=($('woSearch')?.value||'').toLowerCase(),status=$('woFilterStatus')?.value||'',type=$('woFilterType')?.value||'';return st.orders.filter(x=>(!status||x.status===status)&&(!type||x.documentType===type)&&(!q||[x.number,x.customer?.code,x.customer?.name,x.customer?.document,x.machine?.type,x.machine?.brand,x.machine?.model,x.machine?.serial,x.machine?.engineNumber,x.technician,...(x.items||[]).map(i=>`${i.description} ${i.sku}`)].some(v=>String(v||'').toLowerCase().includes(q))))}
function renderOrders(){if(!$('woRows'))return;const rows=orderFiltered().sort((a,b)=>String(b.date||b.createdAtISO||'').localeCompare(String(a.date||a.createdAtISO||'')));$('woHistoryCount').textContent=`${rows.length} registros`;$('woRows').innerHTML=rows.map(x=>`<tr><td><strong>${esc(x.number||'-')}</strong><small>${esc(typeLabel(x.documentType))}</small></td><td>${x.customer?.code?`<small>${esc(x.customer.code)}</small>`:''}<strong>${esc(x.customer?.name||'-')}</strong></td><td><strong>${esc([x.machine?.brand,x.machine?.model].filter(Boolean).join(' ')||x.machine?.type||'-')}</strong><small>${x.machine?.serial?'S/N '+esc(x.machine.serial):''}</small></td><td><span class="wo-status ${esc(x.status)}">${esc(statusLabel(x.status))}</span></td><td><strong>${money(x.total)}</strong></td><td><div class="sales-row-actions"><button class="sales-icon-btn" onclick="KleimpaulOrders.edit('${x.id}')" title="Editar"><i class="fa-solid fa-pen"></i></button><button class="sales-icon-btn" onclick="KleimpaulOrders.print('${x.id}')" title="Imprimir"><i class="fa-solid fa-print"></i></button><button class="sales-icon-btn" onclick="KleimpaulOrders.duplicate('${x.id}')" title="Duplicar"><i class="fa-solid fa-copy"></i></button>${x.documentType!=='os'&&x.status!=='cancelado'?`<button class="sales-icon-btn" onclick="KleimpaulOrders.toOS('${x.id}')" title="Criar O.S."><i class="fa-solid fa-screwdriver-wrench"></i></button>`:''}${x.status!=='cancelado'?`<button class="sales-icon-btn danger" onclick="KleimpaulOrders.cancel('${x.id}')" title="Cancelar"><i class="fa-solid fa-ban"></i></button>`:`<button class="sales-icon-btn danger" onclick="KleimpaulOrders.remove('${x.id}')" title="Excluir definitivamente"><i class="fa-solid fa-trash"></i></button>`}</div></td></tr>`).join('')||'<tr><td colspan="6" class="wo-empty">Nenhum atendimento encontrado.</td></tr>';renderKpis()}
function renderKpis(){const active=st.orders.filter(x=>x.status!=='cancelado'),waiting=active.filter(x=>x.status==='aguardando').length,execution=active.filter(x=>x.status==='execucao').length,approved=active.filter(x=>x.status==='aprovado').length,openValue=active.filter(x=>['aguardando','aprovado','execucao'].includes(x.status)).reduce((a,x)=>a+Number(x.total||0),0);$('woKpiWaiting').textContent=waiting;$('woKpiApproved').textContent=approved;$('woKpiExecution').textContent=execution;$('woKpiValue').textContent=money(openValue)}
function saveDraftNow(){if(!$('woId'))return;try{localStorage.setItem('kleimpaul_work_order_draft',JSON.stringify(currentData()))}catch{}}
const saveDraftDebounced=debounce(saveDraftNow,220);
function restoreDraft(){if(st.draftRestored)return;st.draftRestored=true;try{const raw=localStorage.getItem('kleimpaul_work_order_draft');if(!raw)return;const x=JSON.parse(raw);if(!x||(!x.customerId&&!x.machine?.model&&!x.complaint))return;if(!confirm('Há um atendimento não salvo neste navegador. Recuperar?'))return;$('woNumber').value=x.number||newNumber(x.documentType);$('woType').value=x.documentType||'orcamento';$('woDate').value=x.date||'';$('woValidUntil').value=x.validUntil||'';$('woExpectedDate').value=x.expectedDate||'';$('woStatus').value=x.status||'rascunho';$('woPriority').value=x.priority||'normal';$('woTechnician').value=x.technician||'';$('woCustomer').value=x.customerId||'';updateCustomerUI();$('woMachineType').value=x.machine?.type||'';$('woBrand').value=x.machine?.brand||'STIHL';$('woModel').value=x.machine?.model||'';$('woSerial').value=x.machine?.serial||'';$('woEngineNumber').value=x.machine?.engineNumber||'';$('woAsset').value=x.machine?.asset||'';$('woYear').value=x.machine?.year||'';$('woHourMeter').value=x.machine?.hourMeter||'';$('woFuel').value=x.machine?.fuel||'';$('woCondition').value=x.machine?.condition||'';$('woAccessories').value=x.machine?.accessories||'';$('woComplaint').value=x.complaint||'';$('woDiagnosis').value=x.diagnosis||'';$('woRequestedWork').value=x.requestedWork||'';$('woPerformedWork').value=x.performedWork||'';$('woDiscount').value=x.discount||0;$('woWarranty').value=x.warrantyDays||0;$('woPublicNotes').value=x.publicNotes||'';$('woInternalNotes').value=x.internalNotes||'';$('woApprovalName').value=x.approval?.name||'';$('woApprovalDate').value=x.approval?.date||'';$('woApprovalMethod').value=x.approval?.method||'';$('woApprovalNotes').value=x.approval?.notes||'';st.items=(x.items||[]).map(v=>({...v}));st.photos=x.photos||[];renderItems();renderPhotos();$('woEditState').textContent='RECUPERADO';updateSideStatus()}catch{}}
async function quickCustomer(){const name=$('woQuickName').value.trim();if(!name)return notify('Informe o nome do cliente.','error');const documentValue=$('woQuickDoc').value.trim(),docKey=documentValue.replace(/\D/g,'');if(docKey&&st.customers.some(x=>String(x.document||'').replace(/\D/g,'')===docKey))return notify('Já existe um cliente com este CPF/CNPJ.','error');const nums=st.customers.map(x=>String(x.code||'').match(/^CLI(\d+)$/i)).filter(Boolean).map(m=>Number(m[1])||0),code=`CLI${String(Math.max(0,...nums)+1).padStart(4,'0')}`;const ref=await addDoc(c('customers'),{code,name,document:documentValue,phone:$('woQuickPhone').value.trim(),email:$('woQuickEmail').value.trim(),address:'',stateRegistration:'',createdAt:serverTimestamp(),createdAtISO:iso(),createdAtMs:Date.now(),updatedAt:serverTimestamp(),updatedAtISO:iso()});await audit('customer.create',name,{source:'work_order'});['woQuickName','woQuickDoc','woQuickPhone','woQuickEmail'].forEach(id=>$(id).value='');st.pendingCustomerId=ref.id;setTimeout(()=>{if(st.customers.some(x=>x.id===ref.id))selectCustomer(ref.id)},220);notify('Cliente criado e selecionado.')}
function bind(){if(st.bound)return;st.bound=true;ensureCustomerPicker();$('woStockItem').onchange=stockSelected;$('woStockSearch').oninput=debounce(fillInventory,90);$('woItemAdd').onclick=addItem;$('woPhotoAdd').onclick=addPhoto;$('woNew').onclick=clearForm;$('woSave').onclick=()=>save();$('woAwait').onclick=()=>save('aguardando');$('woComplete').onclick=()=>save('concluido');$('woPrintDraft').onclick=printDraft;if($('woPrintDraftTop'))$('woPrintDraftTop').onclick=printDraft;$('woQuickSave').onclick=quickCustomer;$('woItemImage').addEventListener('focus',loadMedia,{once:true});$('woPhotoSelect').addEventListener('focus',loadMedia,{once:true});$('woType').onchange=()=>{if(!$('woId').value)$('woNumber').value=newNumber($('woType').value);saveDraftDebounced()};$('woStatus').addEventListener('change',()=>{updateSideStatus();saveDraftDebounced()});['woDiscount','woDate','woValidUntil','woExpectedDate','woPriority','woTechnician','woCustomer','woMachineType','woBrand','woModel','woSerial','woEngineNumber','woAsset','woYear','woHourMeter','woFuel','woCondition','woAccessories','woComplaint','woDiagnosis','woRequestedWork','woPerformedWork','woWarranty','woPublicNotes','woInternalNotes','woApprovalName','woApprovalDate','woApprovalMethod','woApprovalNotes','woUseStock'].forEach(id=>$(id)?.addEventListener(['INPUT','TEXTAREA'].includes($(id)?.tagName)?'input':'change',()=>{updateTotals();saveDraftDebounced()}));$('woSearch').oninput=debounce(renderOrders,90);['woFilterStatus','woFilterType'].forEach(id=>$(id).onchange=renderOrders)}
window.KleimpaulOrders={removeItem:i=>{if(st.stockLocked)return notify('Itens bloqueados após a baixa de estoque.','error');st.items.splice(i,1);renderItems()},removePhoto:i=>{st.photos.splice(i,1);renderPhotos()},edit:editOrder,print:printOrder,duplicate:duplicateOrder,toOS:convertToOS,cancel:cancelOrder,remove:deleteOrder};

function injectShortcut(){const actions=document.querySelector('.hero-admin-actions');if(!actions||document.getElementById('ordersDashboardShortcut'))return;const b=document.createElement('button');b.id='ordersDashboardShortcut';b.type='button';b.className='hero-mini';b.innerHTML='<i class="fa-solid fa-screwdriver-wrench"></i> Novo orçamento / O.S.';b.onclick=()=>document.querySelector('[data-go="orders"]')?.click();actions.appendChild(b)}

function maybeRestoreDraft(){if(st.customersLoaded&&st.ordersLoaded)setTimeout(restoreDraft,80)}
function stop(){st.unsubs.forEach(fn=>{try{fn()}catch{}});st.unsubs=[];st.started=false;st.customersLoaded=false;st.ordersLoaded=false}
function start(){if(!st.authorized||st.started||!document.querySelector('[data-section="orders"]')?.classList.contains('active'))return;st.started=true;bind();if(!$('woNumber').value)clearForm();st.unsubs.push(onSnapshot(c('customers'),s=>{st.customers=s.docs.map(v=>({id:v.id,...v.data()})).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));st.customersLoaded=true;fillCustomers();maybeRestoreDraft()}));st.unsubs.push(onSnapshot(c('inventory'),s=>{st.inventory=s.docs.map(v=>({id:v.id,...v.data()}));fillInventory()}));st.unsubs.push(onSnapshot(c('work_orders'),s=>{st.orders=s.docs.map(v=>({id:v.id,...v.data()}));st.ordersLoaded=true;renderOrders();renderCustomerPicker($('woCustomerSearch')?.value||'');updateCustomerUI();if(!$('woId').value)$('woNumber').value=newNumber($('woType').value);maybeRestoreDraft()}))}
function sectionChanged(id){if(id==='orders')start();else if(st.started)stop()}
window.addEventListener('kleimpaul:admin-section',e=>sectionChanged(e.detail?.id));
const obs=new MutationObserver(()=>{const active=document.querySelector('[data-section="orders"]')?.classList.contains('active');if(active)start();else if(st.started)stop()});const orderSection=document.querySelector('[data-section="orders"]');if(orderSection)obs.observe(orderSection,{attributes:true,attributeFilter:['class']});
onAuthStateChanged(auth,user=>{st.authorized=user?.email?.toLowerCase()===EXPECTED;if(st.authorized){bind();injectShortcut();if(document.querySelector('[data-section="orders"]')?.classList.contains('active'))start()}else stop()});
